version: "3.7"
services:
  mysql-db:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rita
    ports:
      - "4823:3306"
  mysql-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mysql-database-admin
    restart: always
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 300M
    ports:
      - "4824:80"