version: "3.7"
services:
  drasdb:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    container_name: drasdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dras
    volumes:
      - ./mysql-files:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - dras
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: drasdb-admin
    environment:
      PMA_HOST: drasdb
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 300M
    ports:
      - "4801:80"
    restart: always
    networks:
      - dras
  dozzle:
    image: amir20/dozzle
    container_name: dras-logs
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    networks:
      - dras
  dras-backend:
    build:
      context: dras-backend
      args:
        DB_IP: drasdb
        DB_PORT: 3306
        DB_NAME: dras
        DB_USERNAME: root
        DB_PASSWORD: root
        RMT: https://rmt.ds.unipi.gr
        REDIS_HOST: drasredis
        REDIS_PORT: 6379
        REDIS_PASSWORD: cU7bUfAKHmvvs4yg
      dockerfile: Dockerfile
    image: dras-backend
    container_name: dras-backend
    ports:
      - "15502:15502"
    restart: always
    depends_on:
      - drasredis
      - drasdb
    networks:
      - dras
  dras-frontend:
    build:
      context: dras-frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:15502/api
    image: dras-frontend
    container_name: dras-frontend
    ports:
      - "5000:80"
    restart: always
    networks:
      - dras
  drasredis:
    image: "redis:alpine"
    container_name: drasredis
    command: redis-server --requirepass cU7bUfAKHmvvs4yg
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - dras
networks:
  dras:
    name: dras
    driver: bridge
