version: "3.7"
services:
  rita-frontend:
    build:
      context: ./rita-frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:15502/api
    image: rita-frontend
    container_name: rita-frontend
    ports:
      - "5000:80"
    restart: unless-stopped
    networks:
      - rita-network
networks:
  rita-network:
    external: true
    name: rita-network
    driver: bridge